# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='MessengerProtoBuff',
  serialized_pb=_b('\n\rmessage.proto\x12\x12MessengerProtoBuff\"8\n\x03Msg\x12\x12\n\nmessage_id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0f\n\x07message\x18\x03 \x02(\t\"a\n\tMsgClient\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x37\n\tchat_type\x18\x02 \x02(\x0e\x32\x1e.MessengerProtoBuff.SelectType:\x04USER\x12\x0f\n\x07message\x18\x03 \x01(\t\":\n\rPostMsgClient\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.MessengerProtoBuff.Msg\"4\n\x06UsrGrp\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x10\n\x08user_ids\x18\x03 \x01(\t\";\n\x0cUsrGrpClient\x12+\n\x07members\x18\x01 \x03(\x0b\x32\x1a.MessengerProtoBuff.UsrGrp*!\n\nSelectType\x12\x08\n\x04USER\x10\x00\x12\t\n\x05GROUP\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SELECTTYPE = _descriptor.EnumDescriptor(
  name='SelectType',
  full_name='MessengerProtoBuff.SelectType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=369,
  serialized_end=402,
)
_sym_db.RegisterEnumDescriptor(_SELECTTYPE)

SelectType = enum_type_wrapper.EnumTypeWrapper(_SELECTTYPE)
USER = 0
GROUP = 1



_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='MessengerProtoBuff.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='MessengerProtoBuff.Msg.message_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='MessengerProtoBuff.Msg.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='MessengerProtoBuff.Msg.message', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=93,
)


_MSGCLIENT = _descriptor.Descriptor(
  name='MsgClient',
  full_name='MessengerProtoBuff.MsgClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MessengerProtoBuff.MsgClient.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chat_type', full_name='MessengerProtoBuff.MsgClient.chat_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='MessengerProtoBuff.MsgClient.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=192,
)


_POSTMSGCLIENT = _descriptor.Descriptor(
  name='PostMsgClient',
  full_name='MessengerProtoBuff.PostMsgClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='MessengerProtoBuff.PostMsgClient.messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=252,
)


_USRGRP = _descriptor.Descriptor(
  name='UsrGrp',
  full_name='MessengerProtoBuff.UsrGrp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MessengerProtoBuff.UsrGrp.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='MessengerProtoBuff.UsrGrp.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_ids', full_name='MessengerProtoBuff.UsrGrp.user_ids', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=306,
)


_USRGRPCLIENT = _descriptor.Descriptor(
  name='UsrGrpClient',
  full_name='MessengerProtoBuff.UsrGrpClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='members', full_name='MessengerProtoBuff.UsrGrpClient.members', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=367,
)

_MSGCLIENT.fields_by_name['chat_type'].enum_type = _SELECTTYPE
_POSTMSGCLIENT.fields_by_name['messages'].message_type = _MSG
_USRGRPCLIENT.fields_by_name['members'].message_type = _USRGRP
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['MsgClient'] = _MSGCLIENT
DESCRIPTOR.message_types_by_name['PostMsgClient'] = _POSTMSGCLIENT
DESCRIPTOR.message_types_by_name['UsrGrp'] = _USRGRP
DESCRIPTOR.message_types_by_name['UsrGrpClient'] = _USRGRPCLIENT
DESCRIPTOR.enum_types_by_name['SelectType'] = _SELECTTYPE

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessengerProtoBuff.Msg)
  ))
_sym_db.RegisterMessage(Msg)

MsgClient = _reflection.GeneratedProtocolMessageType('MsgClient', (_message.Message,), dict(
  DESCRIPTOR = _MSGCLIENT,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessengerProtoBuff.MsgClient)
  ))
_sym_db.RegisterMessage(MsgClient)

PostMsgClient = _reflection.GeneratedProtocolMessageType('PostMsgClient', (_message.Message,), dict(
  DESCRIPTOR = _POSTMSGCLIENT,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessengerProtoBuff.PostMsgClient)
  ))
_sym_db.RegisterMessage(PostMsgClient)

UsrGrp = _reflection.GeneratedProtocolMessageType('UsrGrp', (_message.Message,), dict(
  DESCRIPTOR = _USRGRP,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessengerProtoBuff.UsrGrp)
  ))
_sym_db.RegisterMessage(UsrGrp)

UsrGrpClient = _reflection.GeneratedProtocolMessageType('UsrGrpClient', (_message.Message,), dict(
  DESCRIPTOR = _USRGRPCLIENT,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessengerProtoBuff.UsrGrpClient)
  ))
_sym_db.RegisterMessage(UsrGrpClient)


# @@protoc_insertion_point(module_scope)
